modLoader = "javafml"
loaderVersion = "[46,)"
license = "${mod_license}"
issueTrackerURL = "${mod_issues}"

[[mods]]
modId = "${mod_id}"
version = "${file.jarVersion}"
displayName = "${mod_name}"
displayURL = "${mod_homepage}"
credits = "Thanks for downloading this mod."
authors = "${mod_author}"
description = '''
${mod_description}
'''
itemIcon = "botanypotstiers:elite_terracotta_botany_pot"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "bookshelf"
mandatory = true
versionRange = "[19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "botanypots"
mandatory = true
versionRange = "[12,)"
ordering = "NONE"
side = "BOTH"